// Copyright 2017 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package filesort

import (
	"os"

	"github.com/chrislusf/gleam/sql/sessionctx/variable"
	"github.com/chrislusf/gleam/sql/util/types"
)

type comparableRow struct {
	key    []types.Datum
	val    []types.Datum
	handle int64
}

type item struct {
	index int // source file index
	value *comparableRow
}

// Min-heap of comparableRows
type rowHeap struct {
	sc     *variable.StatementContext
	ims    []*item
	byDesc []bool
	err    error
}

func lessThan(sc *variable.StatementContext, i []types.Datum, j []types.Datum, byDesc []bool) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Len implements heap.Interface Len interface.
func (rh *rowHeap) Len() int {
	_ = "STUB: not implemented"

	// Swap implements heap.Interface Swap interface.
	return 0
}

func (rh *rowHeap) Swap(i, j int) { _ = "STUB: not implemented"; return }

// Less implements heap.Interface Less interface.
func (rh *rowHeap) Less(i, j int) bool { _ = "STUB: not implemented"; return false }

// Push implements heap.Interface Push interface.
func (rh *rowHeap) Push(x interface{}) { _ = "STUB: not implemented"; return }

// Push implements heap.Interface Pop interface.
func (rh *rowHeap) Pop() interface{} { _ = "STUB: not implemented"; return nil }

// FileSorter sorts the given rows according to the byDesc order.
// FileSorter can sort rows that exceed predefined memory capacity.
type FileSorter struct {
	keySize   int                        // size of key slice
	valSize   int                        // size of val slice
	bufSize   int                        // size of buf slice
	tmpDir    string                     // working directory for file sort
	sc        *variable.StatementContext // required by Datum comparison
	buf       []*comparableRow           // in-memory buffer of rows
	files     []string                   // files generated by file sort
	byDesc    []bool                     // whether or not the specific column sorted in descending order
	cursor    int                        // required when performing full in-memory sort
	closed    bool
	fetched   bool
	rowHeap   *rowHeap
	fds       []*os.File
	fileCount int
	err       error
}

// Builder builds a new FileSorter.
type Builder struct {
	sc      *variable.StatementContext
	keySize int
	valSize int
	bufSize int
	byDesc  []bool
	tmpDir  string
}

// SetSC sets StatementContext instance which is required in row comparison.
func (b *Builder) SetSC(sc *variable.StatementContext) *Builder {
	_ = "STUB: not implemented"
	return nil

	// SetSchema sets the schema of row, including key size and value size.
}

func (b *Builder) SetSchema(keySize, valSize int) *Builder { _ = "STUB: not implemented"; return nil }

// SetBuf sets the number of rows FileSorter can hold in memory at a time.
func (b *Builder) SetBuf(bufSize int) *Builder { _ = "STUB: not implemented"; return nil }

// SetDesc sets the ordering rule of row comparison.
func (b *Builder) SetDesc(byDesc []bool) *Builder { _ = "STUB: not implemented"; return nil }

// SetDir sets the working directory for FileSorter.
func (b *Builder) SetDir(tmpDir string) *Builder { _ = "STUB: not implemented"; return nil }

// Build creates a FileSorter instance using given data.
func (b *Builder) Build() (*FileSorter, error) {
	_ = "STUB: not implemented"
	// Sanity checks
	return nil, nil
}

// Len implements sort.Interface Len interface.
func (fs *FileSorter) Len() int {
	_ = "STUB: not implemented"

	// Swap implements sort.Interface Swap interface.
	return 0
}

func (fs *FileSorter) Swap(i, j int) { _ = "STUB: not implemented"; return }

// Less implements sort.Interface Less interface.
func (fs *FileSorter) Less(i, j int) bool { _ = "STUB: not implemented"; return false }

func (fs *FileSorter) getUniqueFileName() string { _ = "STUB: not implemented"; return "" }

// Flush the buffer to file if it is full.
func (fs *FileSorter) flushToFile() error { _ = "STUB: not implemented"; return nil }

// Input adds one row into FileSorter.
// Caller should not call Input after calling Output.
func (fs *FileSorter) Input(key []types.Datum, val []types.Datum, handle int64) error {
	_ = "STUB: not implemented"
	return nil
}

// Sanity checks

// Fetch the next row given the source file index.
func (fs *FileSorter) fetchNextRow(index int) (*comparableRow, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (fs *FileSorter) openAllFiles() error { _ = "STUB: not implemented"; return nil }

func (fs *FileSorter) closeAllFiles() error { _ = "STUB: not implemented"; return nil }

// Close terminates the input or output process and discards all remaining data.
func (fs *FileSorter) Close() error { _ = "STUB: not implemented"; return nil }

// Output gets the next sorted row.
func (fs *FileSorter) Output() ([]types.Datum, []types.Datum, int64, error) {
	_ = "STUB: not implemented"
	return nil, nil, 0, nil
}

// No external files generated.
// Perform full in-memory sort directly.

// Perform full in-memory sort.
func (fs *FileSorter) internalSort() (*comparableRow, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Perform external file sort.
func (fs *FileSorter) externalSort() (*comparableRow, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
